# Використовуємо легку версію Python
FROM python:3.10-slim

# Встановлюємо робочу директорію всередині контейнера
WORKDIR /app

# Копіюємо файл зі списком бібліотек
COPY requirements.txt .

# Встановлюємо залежності
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо ВСІ файли проекту (включаючи loan_model.json та main.py)
COPY . .

# Відкриваємо порт для FastAPI
EXPOSE 8000

# Команда для запуску бота через uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]